POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "jmm",
  "name": "Jennie Monday",
  "password": "abc"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "",
  "name": "",
  "password": ""
}
