POST http://localhost:8080/api/bloglist 
Content-Type: application/json

{
  "title": "How to train your pet dragon",
  "author": "Disney",
  "url": "www.disney.com",
  "userId": "63a0bf218792a1acd387f61f"
}