DELETE http://localhost:3003/api/blogs/63acd2bb4f2b70aec9d603c0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYm1vbmRheSIsImlkIjoiNjNhNDlmODI0MGVhZmUxMzM2ZDc3OTg5IiwiaWF0IjoxNjcyMjg0MTE2fQ.M8mLN44s87LhgBNU6Q0Lcj2ETeM9iSfvKBlHfgURVNg

{
  "userId": "63a49f8240eafe1336d77989"
}