PUT http://localhost:3003/api/blogs/63acbed1fd2eeecff33f9816
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYm1vbmRheSIsImlkIjoiNjNhNDlmODI0MGVhZmUxMzM2ZDc3OTg5IiwiaWF0IjoxNjcxNzMzMzg0fQ.QDINZLivMJaak6cqvVFoUE-eLghMGYabVfmwKL6CtAg

{
  "title": "How to Cook",
  "author": "Rob Monday",
  "url": "www.cookwithcans.com",
  "likes": 991
}

